'use client';

import { getAppSettings, type AppSettings } from '@/lib/settings';

/**
 * ASES — Export Helpers (ported from js/utils/exportHelpers.js)
 * exportToExcel(rows, columns, filename)
 * exportToPDF(rows, columns, title, filename, subtitle, generatedBy)
 * preloadLogoForPDF()  — call once on pages that export PDF
 *
 * College name/subtitle/department/logo come from the `app_settings`
 * table (see lib/settings.ts) rather than being hardcoded here.
 */

const HEADER_H = 46; // mm — table starts below this

export interface ExportColumn {
  header: string;
  key: string;
  width?: number;
  pdfWidth?: number;
}

let logoDataUrl: string | null = null;
let logoLoadStarted = false;

export function preloadLogoForPDF() {
  if (typeof window === 'undefined' || logoLoadStarted) return;
  logoLoadStarted = true;
  getAppSettings().then((settings) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth;
        canvas.height = img.naturalHeight;
        canvas.getContext('2d')?.drawImage(img, 0, 0);
        logoDataUrl = canvas.toDataURL('image/png');
      } catch (e) {
        console.warn('[ASES] Logo preload failed:', (e as Error).message);
      }
    };
    img.src = settings.pdf_logo_url;
  });
}

function getNestedVal(obj: Record<string, unknown>, key: string): unknown {
  if (!obj || !key) return '';
  return key.split('.').reduce<unknown>((acc, k) => (acc != null ? (acc as Record<string, unknown>)[k] : null), obj);
}

export async function exportToExcel(rows: Record<string, unknown>[], columns: ExportColumn[], filename: string) {
  const XLSX = await import('xlsx');
  const headers = columns.map((c) => c.header);
  const data = rows.map((row) => columns.map((c) => getNestedVal(row, c.key) ?? ''));
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet([headers, ...data]);
  ws['!cols'] = columns.map((c) => ({ wch: c.width ?? Math.max(c.header.length + 2, 12) }));
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

export async function exportToPDF(
  rows: Record<string, unknown>[],
  columns: ExportColumn[],
  title: string,
  filename: string,
  subtitle = '',
  generatedBy = ''
) {
  const settings = await getAppSettings();
  const { jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.width;
  drawHeader(doc, pageW, title, subtitle, settings);

  const tableData = rows.map((row) => columns.map((c) => String(getNestedVal(row, c.key) ?? '—')));
  const totalWidth = columns.reduce((sum, c) => sum + (c.pdfWidth || 0), 0);
  const sideMargin = totalWidth > 0 && totalWidth < pageW - 28 ? (pageW - totalWidth) / 2 : 14;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (doc as any).autoTable({
    head: [columns.map((c) => c.header)],
    body: tableData,
    startY: HEADER_H + 4,
    theme: 'grid',
    tableWidth: totalWidth > 0 ? totalWidth : 'auto',
    styles: { fontSize: 7.5, cellPadding: 2, valign: 'middle' },
    headStyles: { fillColor: [26, 34, 68], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 246, 252] },
    columnStyles: Object.fromEntries(columns.map((c, i) => [i, { cellWidth: c.pdfWidth ?? 'auto' }])),
    margin: { top: HEADER_H + 4, left: sideMargin, right: sideMargin },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    didDrawPage(data: any) {
      if (data.pageNumber > 1) drawHeader(doc, pageW, title, subtitle, settings);
      const pageH = doc.internal.pageSize.height;
      const now = new Date();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(80);
      doc.text(`Report Generated By: ${generatedBy || 'ASES'}`, 14, pageH - 9);
      doc.text(
        `Report Generated On: ${now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}  ${now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })}`,
        14,
        pageH - 4.5
      );
      doc.setTextColor(150);
      doc.text(`Page ${data.pageNumber}`, pageW / 2, pageH - 4.5, { align: 'center' });
    },
  });
  doc.save(`${filename}.pdf`);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function drawHeader(doc: any, pageW: number, reportTitle: string, subtitle: string, settings: AppSettings) {
  const cx = pageW / 2;

  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'PNG', 14, 8, 28, 28);
    } catch {
      // ignore
    }
  }

  doc.setFont('times', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(26, 34, 68);
  doc.text(settings.college_name, cx, 16, { align: 'center' });

  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 60, 90);
  doc.text(settings.college_subtitle, cx, 22, { align: 'center' });

  doc.setFont('times', 'bolditalic');
  doc.setFontSize(10.5);
  doc.text(settings.department_name, cx, 28, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(26, 34, 68);
  doc.text(reportTitle, cx, 37, { align: 'center' });

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(90, 100, 120);
    doc.text(subtitle, cx, 43, { align: 'center' });
  }
}
